src/Entity/Plat.php
<?php

namespace App\Entity;

use App\Repository\PlatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=PlatRepository::class)
 * @ORM\Table(name="plat")
 */
class Plat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=Restaurant::class, inversedBy="plats")
     */
    private $restaurants;

    /**
     * @ORM\OneToMany(targetEntity=OrderQuantity::class, mappedBy="plats")
     */
    private $orderQuantities;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="plats")
     */
    private $notes;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $note_moyenne;

    public function __construct()
    {
        $this->orderQuantities = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getRestaurants(): ?Restaurant
    {
        return $this->restaurants;
    }

    public function setRestaurants(?Restaurant $restaurants): self
    {
        $this->restaurants = $restaurants;

        return $this;
    }

    /**
     * @return Collection|OrderQuantity[]
     */
    public function getOrderQuantities(): Collection
    {
        return $this->orderQuantities;
    }

    public function addOrderQuantity(OrderQuantity $orderQuantity): self
    {
        if (!$this->orderQuantities->contains($orderQuantity)) {
            $this->orderQuantities[] = $orderQuantity;
            $orderQuantity->setPlats($this);
        }

        return $this;
    }

    public function removeOrderQuantity(OrderQuantity $orderQuantity): self
    {
        if ($this->orderQuantities->removeElement($orderQuantity)) {
            // set the owning side to null (unless already changed)
            if ($orderQuantity->getPlats() === $this) {
                $orderQuantity->setPlats(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setPlats($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getPlats() === $this) {
                $note->setPlats(null);
            }
        }

        return $this;
    }

    public function getNoteMoyenne(): ?float
    {
        return $this->note_moyenne;
    }

    public function setNoteMoyenne(?float $note_moyenne): self
    {
        $this->note_moyenne = $note_moyenne;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="float")
     */
    private $balance;

    /**
     * @ORM\OneToMany(targetEntity=Restaurant::class, mappedBy="user")
     */
    private $restaurants;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="user")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="user")
     */
    private $notes;

    public function __construct()
    {
        $this->restaurants = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        //$roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getBalance(): ?float
    {
        return $this->balance;
    }

    public function setBalance(float $balance): self
    {
        $this->balance = $balance;

        return $this;
    }

    /**
     * @return Collection|Restaurant[]
     */
    public function getRestaurants(): Collection
    {
        return $this->restaurants;
    }

    public function addRestaurant(Restaurant $restaurant): self
    {
        if (!$this->restaurants->contains($restaurant)) {
            $this->restaurants[] = $restaurant;
            $restaurant->setUser($this);
        }

        return $this;
    }

    public function removeRestaurant(Restaurant $restaurant): self
    {
        if ($this->restaurants->removeElement($restaurant)) {
            // set the owning side to null (unless already changed)
            if ($restaurant->getUser() === $this) {
                $restaurant->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/NoAdminRestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Repository\PlatRepository;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class NoAdminRestaurantController extends AbstractController
{
    /**
     * @Route("/restaurant", name="home")
     */
    public function index(RestaurantRepository $repo): Response
    {
        $restaurants = $repo->findAll();
        return $this->render('no_admin_restaurant/index.html.twig', [
            'restaurants' => $restaurants,
        ]);
    }

    /**
     * @Route("/restaurant/{id}", name="restaurant.show")
     */
    public function showOne(Restaurant $restaurant,PlatRepository $repoPlat): Response
    {
        $plats = $repoPlat->getByID($restaurant->getId());
        return $this->render('no_admin_restaurant/restaurant.html.twig', [
            'restaurant'=>$restaurant,
            'plats' => $plats,
        ]);
    }
}

templates/no_admin_restaurant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Restaurants{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/restaurantsList.css') }}" />
{% endblock %}

{% block body %}

    <main>
        <div class="container">

            {% for restaurant in restaurants %}

                <a class="btn" href="{{ path('restaurant.show', {id: restaurant.id}) }}" role="button">                    
                    <div class="content">
                        <div class="card">
                            <div class="firstinfo"><img src="{{ asset('uploads/' ~ restaurant.logo) }}"/>
                                <div class="profileinfo">
                                    <h1>{{ restaurant.name }}</h1>
                                    <h3>{{ restaurant.address }}, {{ restaurant.postalCode }} {{ restaurant.city }}</h3>
                                    <p class="bio">{{ restaurant.description|striptags|truncate(55, true)|raw }} </p>
                                </div>
                            </div>
                        </div>
                    </div>                
                </a>
                
            {% endfor %}

        </div>
    </main>

{% endblock %}

templates/no_admin_restaurant/restaurant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" href="{{ asset('css/restaurantDetails.css') }}" />
{% endblock %}

{% block body %}

  <div class="container pt-5">
    <div class="row">        
      <div class="col-12">

        <div class="row no-gutters">

            <div class="d-flex">
                <img src="{{ asset('uploads/' ~ restaurant.logo) }}" alt="Illustration of {{restaurant.name}}" class='profil'/>
                <div class="info">
                    <h1 class="card-title">{{restaurant.name}}</h1>
                    <h5>Type : {{restaurant.type.name}} </h5>

                    <p style="text-align: justify;">{{ restaurant.address }}  {{ restaurant.postalCode }},  {{ restaurant.city }}</p>
                </div>
            </div>

            <div class="col-md-12">
                <div class="card-body">
                    <h3 class="card-title">Description : </h3>
                    <p style="text-align: justify;">{{restaurant.description}}</p>                        
                </div>
            </div>

        </div> 
      
        <div class="row justify-content-around">

          {% for plat in plats %}            
            <a class="button" href="#popup-{{plat.id}}">
              <figure>
                <div class="price"><span >{{plat.price}} €</span></div>
                <figcaption>
                  <p></br></p>
                  <img class="imgPlat" src="{{ asset('uploads/' ~ plat.image) }}">
                                        
                </figcaption>
              </figure>
            </a>

            <div class="popup" id="popup-{{plat.id}}">
              <div class="popup-inner">
                <div class="popup__photo">
                  <img class="" src="{{ asset('uploads/' ~ plat.image) }}">
                </div>
                <div class="popup__text">
                  <h2>{{plat.name}}</h2>
                  {% if plat.noteMoyenne == 0  %}
                        {{ include('notation/nullNote.html.twig') }}
                    {% elseif plat.noteMoyenne > 0 and plat.noteMoyenne < 1 %}
                        {{ include('notation/zeroOneNote.html.twig') }}
                    {% elseif plat.noteMoyenne >= 1 and plat.noteMoyenne < 2 %}
                        {{ include('notation/oneNote.html.twig') }}
                    {% elseif plat.noteMoyenne >= 2 and plat.noteMoyenne < 3 %}
                        {{ include('notation/twoNote.html.twig') }}
                    {% elseif plat.noteMoyenne >= 3 and plat.noteMoyenne < 4 %}
                        {{ include('notation/threeNote.html.twig') }}
                  {% elseif plat.noteMoyenne >= 4 and plat.noteMoyenne < 5 %}
                        {{ include('notation/fourNote.html.twig') }}
                    {% else %}
                        {{ include('notation/fiveNote.html.twig') }}
                    {% endif %}

                  <p>{{plat.price}} €</p>

                  {% if app.user %}
                    <a class="btn btnmodal" href="{{ path('cart.add', {id: plat.id}) }}">Ajouter au panier</a>
                  {% else %}
                  <div class="alert alert-warning" role="alert">
                    Une faim ? Connectez-vous pour commander !
                  </div> 
                    
                  {% endif %}
                  
                </div>
                <a class="popup__close" href="#">X</a>
              </div>
            </div>
          {% else %}
            <div class="alert alert-warning" role="alert">
              Aucun plat pour le moment
            </div>
          {% endfor %}
        </div>
            
      </div>                     
    </div>
  </div>

{% endblock %}