src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $ordered_at;

    /**
     * @ORM\Column(type="float")
     */
    private $priceTotal;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="orders")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Restaurant::class, inversedBy="orders")
     */
    private $restaurant;

    /**
     * @ORM\OneToMany(targetEntity=OrderQuantity::class, mappedBy="orders")
     */
    private $orderQuantities;

    public function __construct()
    {
        $this->orderQuantities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderedAt(): ?\DateTimeInterface
    {
        return $this->ordered_at;
    }

    public function setOrderedAt(\DateTimeInterface $ordered_at): self
    {
        $this->ordered_at = $ordered_at;

        return $this;
    }

    public function getPriceTotal(): ?float
    {
        return $this->priceTotal;
    }

    public function setPriceTotal(float $priceTotal): self
    {
        $this->priceTotal = $priceTotal;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): self
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    /**
     * @return Collection|OrderQuantity[]
     */
    public function getOrderQuantities(): Collection
    {
        return $this->orderQuantities;
    }

    public function addOrderQuantity(OrderQuantity $orderQuantity): self
    {
        if (!$this->orderQuantities->contains($orderQuantity)) {
            $this->orderQuantities[] = $orderQuantity;
            $orderQuantity->setOrders($this);
        }

        return $this;
    }

    public function removeOrderQuantity(OrderQuantity $orderQuantity): self
    {
        if ($this->orderQuantities->removeElement($orderQuantity)) {
            // set the owning side to null (unless already changed)
            if ($orderQuantity->getOrders() === $this) {
                $orderQuantity->setOrders(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="float")
     */
    private $balance;

    /**
     * @ORM\OneToMany(targetEntity=Restaurant::class, mappedBy="user")
     */
    private $restaurants;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="user")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="user")
     */
    private $notes;

    public function __construct()
    {
        $this->restaurants = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        //$roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getBalance(): ?float
    {
        return $this->balance;
    }

    public function setBalance(float $balance): self
    {
        $this->balance = $balance;

        return $this;
    }

    /**
     * @return Collection|Restaurant[]
     */
    public function getRestaurants(): Collection
    {
        return $this->restaurants;
    }

    public function addRestaurant(Restaurant $restaurant): self
    {
        if (!$this->restaurants->contains($restaurant)) {
            $this->restaurants[] = $restaurant;
            $restaurant->setUser($this);
        }

        return $this;
    }

    public function removeRestaurant(Restaurant $restaurant): self
    {
        if ($this->restaurants->removeElement($restaurant)) {
            // set the owning side to null (unless already changed)
            if ($restaurant->getUser() === $this) {
                $restaurant->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Note;
use App\Entity\Order;
use App\Entity\OrderQuantity;
use App\Entity\Plat;
use App\Entity\User;
use App\Form\NoteType;
use App\Form\UserFormType;
use App\Repository\NoteRepository;
use App\Repository\OrderQuantityRepository;
use App\Repository\OrderRepository;
use App\Repository\UserRepository;
use DateTime;
use Doctrine\Bundle\DoctrineBundle\Registry;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/profil/", name="profil.show", methods={"GET"}) 
     */
    public function show(UserRepository $userRepo): Response
    {
        $user=$this->getUser();
        $user=$userRepo->find($user->getId());
        return $this->render('user/profil.html.twig', [
            'user' => $user,
        ]);
    }
    /**
     * @Route("/profil/edit", name="profil.edit", methods={"GET","POST"})
     */
    public function editUser(Request $request, EntityManagerInterface $em, UserRepository $userRepo): Response
    {
        $user=$this->getUser();
        $user=$userRepo->find($user->getId());
        $form = $this->createForm(UserFormType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('profil.show');
        }
        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("admin/profil/{id}/edit", name="admin.profil.edit", methods={"GET","POST"})
     */
    public function adminEditUser(Request $request, EntityManagerInterface $em, User $user): Response
    {
        $form = $this->createForm(UserFormType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('profil.show');
        }
        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }
    
    public function PREFABorderList(OrderRepository $orderRepo)
    {
        $orders = $orderRepo->findBy(['user'=>$this->getUser()]);
        $orderList = [];
        $orderEncours = [];
        $orderLivre = [];
        foreach($orders as $order)
        {
            if($order->getOrderedAt()< new DateTime()){
                $orderLivre[] = $orderRepo->find($order);
            }else{
                $orderEncours[] = $orderRepo->find($order);
            }
        }

        $orderList = [$orderEncours,$orderLivre];
        return $orderList;
    }


    /**
     * @Route("/profil/order", name="profil.order", methods={"GET"})
     */
    public function orderList(OrderRepository $orderRepo)
    {
        $orders = $this->PREFABorderList($orderRepo);
        $orders = array_merge($orders[0], $orders[1]);
        return $this->render('user/orderList.html.twig', [
            'orders' => $orders,
            'title' => 'Toutes vos commandes',
            'empty' => 'Aucune commande',
        ]);
    }
    
    /**
     * @Route("/profil/orders/progress", name="profil.order.progress", methods={"GET"})
     */
    public function ProgressList(OrderRepository $orderRepo)
    {
        $orders = $this->PREFABorderList($orderRepo);
        $orderEncours = $orders[0];
        return $this->render('user/orderList.html.twig', [
            'orders' => $orderEncours,
            'title' => 'Vos commandes en cours',
            'empty' => 'Aucune commande en cours'
        ]);

    }

    /**
     * @Route("/profil/order/delivered", name="profil.order.delivered", methods={"GET"})
     */
    public function DeliveredList(OrderRepository $orderRepo)
    {
        $orders = $this->PREFABorderList($orderRepo);
        $orderLivre = $orders[1];
        return $this->render('user/orderDelivered.html.twig', [
            'orders' => $orderLivre,
            'title' => 'Vos commandes livrées',
            'empty' => 'Aucune commande livrée'
        ]);
    }

    /**
     * @Route("/profil/order/delivered/{id}", name="profil.order.show", methods={"GET"})
     */
    public function showOrder(Order $order, OrderQuantityRepository $repo)
    {
        $user = $this->getUser();
        $verifUser = $order->getUser();
        if($verifUser == $user){
            $orderQuantities = $repo->findBy([
                'orders' => $order
            ]);
            return $this->render('user/orderMore.html.twig', [
                'orders' => $orderQuantities,
            ]);
        }else{
            return $this->redirectToRoute('profil.order.delivered');
        }
    }

    /**
     * @Route("/profil/order/delivered/{order}/{plat}", name="profil.order.note", methods={"GET","POST"})
     */
    public function note(Order $order, Plat $plat, Request $request, EntityManagerInterface $em, NoteRepository $noteRepo, OrderQuantityRepository $orderRepo)
    {
        $user = $this->getUser();
        $note = new Note();
        $form = $this->createForm(NoteType::class,$note);
        $form->handleRequest($request);
        $verifUser = $order->getUser();
        $verifOrders = $orderRepo->findBy([
            'plats' => $plat
        ]);
        foreach($verifOrders as $verifOrder){
            if($verifOrder->getOrders() == $order){
                $verif = true;
                $verifOrderDate = $verifOrder->getOrders();
            }
        }
        $datehier = New DateTime('-1 day +1 hour');
        $dateLivre = New DateTime();
        $verifDate = $verifOrderDate->getOrderedAt();
        if($verifUser == $user && $verif == true ){
            if($dateLivre > $verifDate && $verifDate > $datehier){
                if ($form->isSubmitted() && $form->isValid()) {
                    $existingNote = $noteRepo->findOneBy([
                        'plats' => $plat,
                        'user' => $user
                    ]);
        
                    $noteplats = $noteRepo->findBy([
                        'plats' => $plat
                    ]);
                    $notes = [];
                    foreach($noteplats as $noteplat){
                        $notes[] = $noteplat->getNote();
                    }
            
                    if($existingNote == null){
                        $note->setPlats($plat)
                            ->setUser($user);
        
                        $notes[] = $note->getNote();
                        $em->persist($note);
                    }else{
                        if(count($notes) == 1){
                            $notes = [];
                        }else{
                            $lanote = $existingNote->getNote();
                            unset($notes[array_search($lanote,$notes)]);
                        }
                        $existingNote->setNote($note->getNote());
                        $notes[] = $note->getNote();
                    }
    
                    $noteMoyenne = array_sum($notes)/(count($notes));
                    $plat->setNoteMoyenne($noteMoyenne);
                    $em->flush();
                    
                    return $this->redirectToRoute('profil.order.delivered');
                }
                return $this->render('user/newNote.html.twig',[
                    'plat' => $plat,
                    'form' => $form->createView(),
                ]);
            }else{
                return $this->redirectToRoute('profil.order.delivered');
            }
            
            
        }else{
            return $this->redirectToRoute('profil.order.delivered');
        }
    }
}

templates/user/_form.html.twig
<container>
    {{ form_start(form) }}
        <div class="d-flex justify-content-between">
            {{ form_row(form.name, {
                label: 'Nom','attr':{'class': 'form-control','placeholder' :'Nom'}
            }) }}
            {{ form_row(form.firstName, {
                label: 'Prénom','attr':{'class': 'form-control','placeholder' :'Prénom'}
            }) }}
        </div>
        {{ form_row(form.email,  {
            label: 'Email','attr':{'class': 'form-control','placeholder' :'Votre Email'}
        }) }}                              
        {{ form_row(form.address, {
            label: 'Adresse','attr':{'class': 'form-control','placeholder' :'Votre Adresse'}
        }) }}
        <div class="d-flex justify-content-between">
            {{ form_row(form.postal_code, { 
                label: 'Code Postal',
                'attr':{'class': 'form-control','placeholder' :'Code Postal','type':'number',  'maxlength': '5'  }
            }) }}
            {{ form_row(form.city, {
                label: 'Ville','attr':{'class': 'form-control','placeholder' :'Votre ville'}
            }) }}
        </div>
        {{ form_row(form._token) }}
        <button type="submit" class="btn  btn-warning btn-lg">Editer</button>
    {{ form_end(form, {'render_rest': false}) }}
</container>

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/profil.css') }}" />
{% endblock %}
{% block body %}


    <div class="container pt-5 mt-5">
        <div class="row">

            <section class="boutton">
                <div class="col-12 col-md-5">
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.show') }}">Profil</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.progress') }}">Commandes en cours</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.delivered') }}">Commandes livrées</a>
                    </div>
                    
                </div>
            </section>
            
            <div class="col-12 col-md-8">
                <h3>Editer mon profil </h3>

              {{ include('/user/_form.html.twig', {'button_label': 'Update'}) }}
                
                
            </div>

        </div>
    </div>


    

{% endblock %}

templates/user/newNote.html.twig
{% extends 'base.html.twig' %}

{% block title %}Notation d'un plat{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/profil.css') }}" />
{% endblock %}

{% block body %}

    <div class="container pt-5 mt-5">
        <div class="row">

            <section class="boutton">
                <div class="col-12 col-md-5">
                    <div class="btn-1">
                        <a  class="btn btn-lg btn-outline-warning"href="{{ path('profil.show') }}">Profil</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.progress') }}">Commandes en cours</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.delivered') }}">Commandes livrées</a>
                    </div>
                    
                </div>
            </section>
            
            <div class="col-12 col-md-9">
            
                <h3>Notation d'un plat : </h3>
                {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <button class="btn btn-warning">{{ button_label|default('Je valide !') }}</button>
                {{ form_end(form) }}

            </div>
  
        </div>
    </div>
          
{% endblock %}

templates/user/orderDelivered.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commandes livrées{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/profil.css') }}" />
{% endblock %}

{% block body %}

    <div class="container pt-5 mt-5">
        <div class="row">

            <section class="boutton">
                <div class="col-12 col-md-5">
                    <div class="btn-1">
                        <a  class="btn btn-lg btn-outline-warning"href="{{ path('profil.show') }}">Profil</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.progress') }}">Commandes en cours</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.delivered') }}">Commandes livrées</a>
                    </div>
                    
                </div>
            </section>
            
            <div class="col-12 col-md-9">
            
                <h3>{{title}}</h3>
                {% for order in orders %}
                    <div class="cart shadow p-3 mb-5 bg-white rounded">
                        <div class="cart-content p-4">
                            <div class="d-flex justify-content-around">
                                <div class="id">#{{ order.id }}</div>
                                <div class="date"><b>Date :</b> {{ order.orderedAt | date('Y-m-d H:i:s') }}</div>
                                <div class="restaurant"><b>Restaurant :</b> {{ order.restaurant.name }}</div>
                                <div class="price"><b>Prix Total :</b> {{ order.priceTotal}}€</div>
                                <a class="btn btn-outline-warning" style="margin-left:1em;" href="{{ path('profil.order.show', {id: order.id}) }}">Details</a>                            
                            </div>
                        </div>
                    </div>            
                {% else %}               
                    <div class="cart shadow p-3 mb-5 bg-white rounded">
                        <div class="cart-content p-4">
                        {{empty}}
                        </div>
                    </div>
                {% endfor %}
                
            </div>
                
        </div>
    </div>

{% endblock %}

templates/user/orderList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des commandes{% endblock %}

{% block stylesheets %}
      <link rel="stylesheet" href="{{ asset('css/profil.css') }}" />
{% endblock %}

{% block body %}

    <div class="container pt-5 mt-5">
        <div class="row">

            <section class="boutton">                   
                <div class="col-12 col-md-5">
                    <div class="btn-1">
                        <a  class="btn btn-lg btn-outline-warning"href="{{ path('profil.show') }}">Profil</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.progress') }}">Commande en cours</a>
                    </div>
                    <div class="btn-1">
                        <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.delivered') }}">Commandes livrées</a>
                    </div>
                    
                </div>
            </section>
            
            <div class="col-12 col-md-9">
            
                <h3>{{title}}</h3>
                {% for order in orders %}
                    <div class="cart shadow p-3 mb-5 bg-white rounded">
                        <div class="cart-content p-4">
                            <div class="d-flex justify-content-around">
                                <div class="id">#{{ order.id }}</div>
                                <div class="date"><b>Date :</b> {{ order.orderedAt | date('Y-m-d H:i:s') }}</div>
                                <div class="restaurant"><b>Restaurant :</b> {{ order.restaurant.name }}</div>
                                <div class="price"><b>Prix Total :</b> {{ order.priceTotal}}€</div>
                            </div>
                        </div>
                    </div>
                {% else %}                
                    <div class="cart shadow p-3 mb-5 bg-white rounded">
                        <div class="cart-content p-4">
                        {{empty}}
                        </div>
                    </div>
               {% endfor %}
               
            </div>

        </div>
    </div>
            
{% endblock %}

templates/user/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre profil{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/profil.css') }}" />
{% endblock %}

{% block body %}

    <div class="container pt-5 mt-5">
        <div class="row">

            <section class="recherche">

                <section class="boutton">
                    <div class="col-12 col-md-5">
                        <div class="btn-1">
                            <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.edit') }}">Editer le profil</a>
                        </div>
                        <div class="btn-1">
                            <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.progress') }}">Commandes en cours</a>
                        </div>
                        <div class="btn-1">
                            <a class="btn btn-lg btn-outline-warning" href="{{ path('profil.order.delivered') }}">Commandes livrées</a>
                        </div>
                        
                    </div>
                </section>

                <div class="col-6 col-md-7">
                    <h3>Mon profil : </h3>
                    <div class="row shadow p-3 mb-5 bg-white rounded">
                        <div class="col-sm-2 col-md-3">
                            <img src="../img/user-profile.png"  alt="" class="img-rounded img-responsive" />
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <blockquote>
                                <p>{{user.name}} {{user.firstName}}</p> <small><cite title="Source Title">{{user.address}}, {{user.postalCode}} {{user.city}}  <i class="glyphicon glyphicon-map-marker"></i></cite></small>
                            </blockquote>
                            <p> <i class="glyphicon glyphicon-envelope"></i> {{user.email}}
                                <br> <i class="glyphicon glyphicon-globe"></i> Balance : {{user.balance}}
                            </p>
                        </div>
                    </div>                                  
                </div>

            </section>

        </div>
    </div>

{% endblock %}